In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
url='https://npb.jp/bis/2021/stats/tmb_c.html'
dfs=pd.read_html(url)
df=dfs[0]
display(df)

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二塁打,三塁打,本塁打,...,盗塁刺,犠 打,犠 飛,四 球,故意四,死 球,三 振,併殺打,長打率,出塁率
0,広 島,0.264,143,5361,4798,557,1265,200,17,123,...,40,85,34,402,24,42,1015,94,0.389,0.324
1,DeNA,0.258,143,5340,4784,559,1233,254,13,136,...,27,81,24,407,18,43,1028,107,0.402,0.320
2,ヤクルト,0.254,143,5399,4708,625,1196,214,17,142,...,32,90,27,513,22,61,1079,105,0.397,0.333
3,阪 神,0.247,143,5265,4704,541,1164,208,23,121,...,30,82,33,406,22,40,1082,95,0.379,0.311
4,巨 人,0.242,143,5241,4692,552,1137,207,11,169,...,36,48,27,431,22,43,1157,98,0.399,0.310
5,中 日,0.237,143,5073,4595,405,1090,182,21,69,...,36,98,23,326,26,31,973,104,0.331,0.291